---
- name: Conditional Tekton Helm Installation
  hosts: localhost
  vars_files:
      - gcd.yml

  tasks:
      - name: Pause for a few seconds
        pause:
            seconds: 10

      - name: Generate YAML file from variables
        copy:
            content: |
                gitSecret:
                  username: "{{ gitSecret.username }}"
                  password: "{{ gitSecret.password }}"
                docker:
                  configJson: "{{ docker.configJson }}"
            dest: "../tekton-resource/values.yaml"

      - block:
            - name: Install Tekton resource
              command:
                  cmd: helm install tekton-resource ../tekton-resource
              register: helm_install_output

            - name: Print Helm Install Output
              debug:
                  msg: "{{ helm_install_output.stdout_lines }}"

            - name: Pause for a few seconds
              pause:
                  seconds: 10

            - name: install tekton polling crd
              command:
                  cmd: kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.14.2/release.yaml
              register: install_tekton_polling_crd
              ignore_errors: yes

            - name: Print install tekton polling crd
              debug:
                  msg: "{{install_tekton_polling_crd}}"

            - name: Pause for a few seconds
              pause:
                  seconds: 10

            # - name: install tekton polling operator
            #   command:
            #     cmd: kubectl apply -f https://github.com/bigkevmcd/tekton-polling-operator/releases/download/v0.4.0/release-v0.4.0.yaml
            #   register: install_tekton_polling_operator

            # - name: Print install tekton polling operator
            #   debug:
            #     msg: "{{install_tekton_polling_operator}}"

            - name: Pause for a few seconds
              pause:
                  seconds: 30

        rescue:
            - name: Print Error Message
              debug:
                  msg: "Tekton Helm installation failed"
